# Generated for Trainova upgraded build
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('body_part', models.CharField(max_length=80)),
                ('target_muscle', models.CharField(max_length=80)),
                ('secondary_muscles', models.CharField(blank=True, max_length=255)),
                ('equipment', models.CharField(default='Bodyweight', max_length=80)),
                ('difficulty', models.CharField(default='Beginner', max_length=40)),
                ('movement_pattern', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('safety_tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_images/')),
                ('external_image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('focus', models.CharField(default='Full Body', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(default='Beginner', max_length=40)),
                ('days_per_week', models.PositiveIntegerField(default=3)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(default='Nairobi', max_length=80)),
                ('age', models.PositiveIntegerField(default=28)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('height_cm', models.FloatField(default=170)),
                ('weight_kg', models.FloatField(default=70)),
                ('target_weight_kg', models.FloatField(blank=True, null=True)),
                ('goal', models.CharField(choices=[('fat_loss', 'Fat loss'), ('muscle_gain', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('general_fitness', 'General fitness'), ('rehab', 'Rehabilitation')], default='general_fitness', max_length=40)),
                ('training_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=40)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('athlete', 'Athlete')], default='moderate', max_length=40)),
                ('weekly_target', models.PositiveIntegerField(default=4)),
                ('available_equipment', models.CharField(default='Bodyweight, Dumbbells', max_length=255)),
                ('injury_notes', models.TextField(blank=True)),
                ('medical_clearance_confirmed', models.BooleanField(default=False)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('readiness_status', models.CharField(default='Good', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseAngleStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Front knee angle, hip hinge angle', max_length=120)),
                ('joint_a', models.CharField(help_text='First landmark name', max_length=80)),
                ('joint_b', models.CharField(help_text='Middle/vertex landmark name', max_length=80)),
                ('joint_c', models.CharField(help_text='Third landmark name', max_length=80)),
                ('min_degrees', models.FloatField()),
                ('max_degrees', models.FloatField()),
                ('feedback_when_low', models.CharField(blank=True, max_length=255)),
                ('feedback_when_high', models.CharField(blank=True, max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_standards', to='trainova.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reference_media/')),
                ('external_url', models.URLField(blank=True)),
                ('coaching_notes', models.TextField(blank=True)),
                ('is_correct_form', models.BooleanField(default=True)),
                ('landmark_data', models.JSONField(blank=True, default=dict)),
                ('overlay_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='trainova.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('category', models.CharField(default='training', max_length=40)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('weight', 'Body weight'), ('body_fat', 'Body fat'), ('waist', 'Waist'), ('chest', 'Chest'), ('hip', 'Hip'), ('arm', 'Arm'), ('thigh', 'Thigh'), ('resting_hr', 'Resting heart rate'), ('sleep', 'Sleep hours'), ('water', 'Water intake'), ('steps', 'Steps'), ('calories', 'Calories'), ('protein', 'Protein'), ('readiness', 'Readiness score'), ('workout_volume', 'Workout volume')], max_length=80)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='', max_length=20)),
                ('recorded_at', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['recorded_at']},
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(default='completed', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=45)),
                ('perceived_exertion', models.PositiveIntegerField(default=6)),
                ('calories_estimate', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainova.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_label', models.CharField(default='Day 1', max_length=50)),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='8-12', max_length=50)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainova.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trainova.workoutplan')),
            ],
            options={'ordering': ['order']},
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Guest User', max_length=120)),
                ('uploaded_file', models.FileField(upload_to='user_form_uploads/')),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(default='processed', max_length=30)),
                ('feedback', models.JSONField(blank=True, default=list)),
                ('analysis_summary', models.TextField(blank=True)),
                ('detected_landmarks', models.JSONField(blank=True, default=dict)),
                ('reference_landmarks', models.JSONField(blank=True, default=dict)),
                ('angle_results', models.JSONField(blank=True, default=list)),
                ('overlay_coordinates', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to='trainova.exercise')),
                ('reference_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainova.referencemedia')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
